# Import Libraries

In [1]:
# Standard libraries
import numpy as np
import pandas as pd
pd.set_option('display.max_rows', 300)

# for audio files
import librosa

In [2]:
from google.colab import drive
import os
drive.mount('/content/drive')

Mounted at /content/drive


# Load training data csv file

In [3]:
df = pd.read_csv('/content/drive/MyDrive/207/207-Project/data/test_metadata.csv')

df.head()

primary_label         common_name    scientific_name  species_rank  \
0       thrnig1  Thrush Nightingale  Luscinia luscinia             0   
1       thrnig1  Thrush Nightingale  Luscinia luscinia             0   
2       thrnig1  Thrush Nightingale  Luscinia luscinia             0   
3       thrnig1  Thrush Nightingale  Luscinia luscinia             0   
4       thrnig1  Thrush Nightingale  Luscinia luscinia             0   

               filename dataset  duration_secs  duration_mins  duration_hrs  \
0  thrnig1/XC112492.ogg    test      58.540408       0.975673      0.016261   
1  thrnig1/XC132295.ogg    test      73.769796       1.229497      0.020492   
2  thrnig1/XC133558.ogg    test      78.759229       1.312654      0.021878   
3  thrnig1/XC134265.ogg    test     394.187755       6.569796      0.109497   
4  thrnig1/XC135792.ogg    test      42.344535       0.705742      0.011762   

   species_total_files  ...  rating  latitude  longitude            author  \
0                  499  ...     3.0   59.8510    17.6230        Sander Bot   
1                  499  ...     3.0   56.0889    47.2543  Albert Lastukhin   
2                  499  ...     4.5   61.5650    29.5650     Stuart Fisher   
3                  499  ...     5.0   51.3506    23.0467    Jarek Matusiak   
4                  499  ...     3.0   56.7542    46.8450  Albert Lastukhin   

                                 url  \
0  https://www.xeno-canto.org/112492   
1  https://www.xeno-canto.org/132295   
2  https://www.xeno-canto.org/133558   
3  https://www.xeno-canto.org/134265   
4  https://www.xeno-canto.org/135792   

                                             license  class_weight_file  \
0  Creative Commons Attribution-NonCommercial-Sha...           0.937876   
1  Creative Commons Attribution-NonCommercial-Sha...           0.937876   
2  Creative Commons Attribution-NonCommercial-Sha...           0.937876   
3  Creative Commons Attribution-NonCommercial-Sha...           0.937876   
4  Creative Commons Attribution-NonCommercial-Sha...           0.937876   

   class_weight_duration  class_weight_combined  orig_index  
0               0.419757               0.627439       13847  
1               0.419757               0.627439       13856  
2               0.419757               0.627439       13859  
3               0.419757               0.627439       13860  
4               0.419757               0.627439       13866  

[5 rows x 34 columns]

# Define extract audio function to ensure sample rate and extract audio object in np.array format using librosa

In [4]:
def extract_audio_librosa(filename, desired_sample_rate=16000):
  '''
  Usage: extract the audio object in np.array format from an audio file
  Input:
    filename
  Output:
    audio object in np.array format
  '''
  filepath = '/content/drive/MyDrive/207/207-Project/data/test/audio_files/' + filename
  waveform, sample_rate = librosa.load(filepath, sr=desired_sample_rate)
  if sample_rate != desired_sample_rate:
    waveform = librosa.resample(y=waveform, orig_sr = sample_rate, target_sr = desired_sample_rate)
  return waveform

# Extract file names

In [5]:
filenames = df['filename']
filenames

0       thrnig1/XC112492.ogg
1       thrnig1/XC132295.ogg
2       thrnig1/XC133558.ogg
3       thrnig1/XC134265.ogg
4       thrnig1/XC135792.ogg
                ...         
1397    cohmar1/XC748720.ogg
1398    cohmar1/XC748721.ogg
1399    cohmar1/XC748725.ogg
1400    cohmar1/XC749488.ogg
1401    cohmar1/XC749637.ogg
Name: filename, Length: 1402, dtype: object

# Create top level directory to save the files

In [6]:
save_dir = '/content/drive/MyDrive/207/207-Project/data/test/librosa_loaded'

In [7]:
os.makedirs(save_dir, exist_ok=False)

# Create a list to store the file paths

In [8]:
filepaths = []

# Extract the audio files and save to disk

In [9]:
for i, filename in enumerate(filenames):
  audio = extract_audio_librosa(filename)

  dir = filename.split('/')[0]
  filename = filename.split('/')[1]
  filename = filename.replace('.ogg', '.npy')
  save_dir = f'/content/drive/MyDrive/207/207-Project/data/test/librosa_loaded/{dir}/'

  if os.path.exists(save_dir):
    pass
  else:
    os.makedirs(save_dir, exist_ok=True)

  save_filename = os.path.join(save_dir, filename)

  filepath = f'{dir}/{filename}'
  filepaths.append(filepath)

  with open(save_filename, 'w') as file:
    pass

  np.save(save_filename, audio)

  del audio
  del filepath

# Pick an example to ensure the audio object was saved successfully and correctly

In [10]:
example_b4 = extract_audio_librosa(filenames[0])
example_b4

array([-2.2763852e-06, -7.0454553e-07,  2.2521708e-06, ...,
        1.3894627e-05, -2.4790970e-05,  1.7528437e-05], dtype=float32)

In [11]:
example_b4.shape

(936647,)

In [12]:
example = np.load('/content/drive/MyDrive/207/207-Project/data/test/librosa_loaded/thrnig1/XC112492.npy')
example

array([-2.2763852e-06, -7.0454553e-07,  2.2521708e-06, ...,
        1.3894627e-05, -2.4790970e-05,  1.7528437e-05], dtype=float32)

In [13]:
example.shape

(936647,)

In [14]:
np.array_equal(example_b4, example)

True

# Pick another example to ensure the audio object was saved successfully and correctly

In [15]:
example_b4 = extract_audio_librosa(filenames[1401])
example_b4

array([9.5530231e-07, 1.3598146e-06, 1.3222638e-05, ..., 1.1540429e-05,
       3.8615424e-05, 9.9565486e-06], dtype=float32)

In [16]:
example_b4.shape

(80640,)

In [17]:
example = np.load('/content/drive/MyDrive/207/207-Project/data/test/librosa_loaded/cohmar1/XC749637.npy')
example

array([9.5530231e-07, 1.3598146e-06, 1.3222638e-05, ..., 1.1540429e-05,
       3.8615424e-05, 9.9565486e-06], dtype=float32)

In [18]:
example.shape

(80640,)

In [19]:
np.array_equal(example_b4, example)

True

# check that the filepaths were all saved correctly and add that to the original df

In [20]:
filepaths

['thrnig1/XC112492.npy',
 'thrnig1/XC132295.npy',
 'thrnig1/XC133558.npy',
 'thrnig1/XC134265.npy',
 'thrnig1/XC135792.npy',
 'thrnig1/XC152472.npy',
 'thrnig1/XC152506.npy',
 'thrnig1/XC176969.npy',
 'thrnig1/XC178171.npy',
 'thrnig1/XC179283.npy',
 'thrnig1/XC180341.npy',
 'thrnig1/XC180896.npy',
 'thrnig1/XC181942.npy',
 'thrnig1/XC185981.npy',
 'thrnig1/XC186525.npy',
 'thrnig1/XC193316.npy',
 'thrnig1/XC194398.npy',
 'thrnig1/XC197641.npy',
 'thrnig1/XC198467.npy',
 'thrnig1/XC198989.npy',
 'thrnig1/XC199723.npy',
 'thrnig1/XC208268.npy',
 'thrnig1/XC208335.npy',
 'thrnig1/XC208336.npy',
 'thrnig1/XC239956.npy',
 'thrnig1/XC243985.npy',
 'thrnig1/XC243986.npy',
 'thrnig1/XC247794.npy',
 'thrnig1/XC25659.npy',
 'thrnig1/XC25663.npy',
 'thrnig1/XC272274.npy',
 'thrnig1/XC27290.npy',
 'thrnig1/XC287206.npy',
 'thrnig1/XC298473.npy',
 'thrnig1/XC315417.npy',
 'thrnig1/XC316859.npy',
 'thrnig1/XC318060.npy',
 'thrnig1/XC319070.npy',
 'thrnig1/XC320149.npy',
 'thrnig1/XC322370.npy',
 't

In [21]:
len(df) == len(filepaths)

True

In [22]:
df['librosa_loaded'] = filepaths

In [23]:
df.head()

primary_label         common_name    scientific_name  species_rank  \
0       thrnig1  Thrush Nightingale  Luscinia luscinia             0   
1       thrnig1  Thrush Nightingale  Luscinia luscinia             0   
2       thrnig1  Thrush Nightingale  Luscinia luscinia             0   
3       thrnig1  Thrush Nightingale  Luscinia luscinia             0   
4       thrnig1  Thrush Nightingale  Luscinia luscinia             0   

               filename dataset  duration_secs  duration_mins  duration_hrs  \
0  thrnig1/XC112492.ogg    test      58.540408       0.975673      0.016261   
1  thrnig1/XC132295.ogg    test      73.769796       1.229497      0.020492   
2  thrnig1/XC133558.ogg    test      78.759229       1.312654      0.021878   
3  thrnig1/XC134265.ogg    test     394.187755       6.569796      0.109497   
4  thrnig1/XC135792.ogg    test      42.344535       0.705742      0.011762   

   species_total_files  ...  latitude  longitude            author  \
0                  499  ...   59.8510    17.6230        Sander Bot   
1                  499  ...   56.0889    47.2543  Albert Lastukhin   
2                  499  ...   61.5650    29.5650     Stuart Fisher   
3                  499  ...   51.3506    23.0467    Jarek Matusiak   
4                  499  ...   56.7542    46.8450  Albert Lastukhin   

                                 url  \
0  https://www.xeno-canto.org/112492   
1  https://www.xeno-canto.org/132295   
2  https://www.xeno-canto.org/133558   
3  https://www.xeno-canto.org/134265   
4  https://www.xeno-canto.org/135792   

                                             license  class_weight_file  \
0  Creative Commons Attribution-NonCommercial-Sha...           0.937876   
1  Creative Commons Attribution-NonCommercial-Sha...           0.937876   
2  Creative Commons Attribution-NonCommercial-Sha...           0.937876   
3  Creative Commons Attribution-NonCommercial-Sha...           0.937876   
4  Creative Commons Attribution-NonCommercial-Sha...           0.937876   

   class_weight_duration  class_weight_combined  orig_index  \
0               0.419757               0.627439       13847   
1               0.419757               0.627439       13856   
2               0.419757               0.627439       13859   
3               0.419757               0.627439       13860   
4               0.419757               0.627439       13866   

         librosa_loaded  
0  thrnig1/XC112492.npy  
1  thrnig1/XC132295.npy  
2  thrnig1/XC133558.npy  
3  thrnig1/XC134265.npy  
4  thrnig1/XC135792.npy  

[5 rows x 35 columns]

# load one example from df and use in a librosa function to confirm the object is usable

In [24]:
example_og = extract_audio_librosa(df['filename'][0])
example_og_rms = librosa.feature.rms(y=example_og)
example_og_rms

array([[0.00618627, 0.0077443 , 0.01076956, ..., 0.00737438, 0.00637029,
        0.0050477 ]], dtype=float32)

In [25]:
example_new = np.load('/content/drive/MyDrive/207/207-Project/data/test/librosa_loaded/' + df['librosa_loaded'][0])
example_new_rms = librosa.feature.rms(y=example_new)
example_new_rms

array([[0.00618627, 0.0077443 , 0.01076956, ..., 0.00737438, 0.00637029,
        0.0050477 ]], dtype=float32)

In [26]:
np.array_equal(example_og_rms, example_new_rms)

True